version: '2'

services:
  nginx:
    image: nginx:alpine
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./client/dist:/usr/share/nginx/html

  netcore:
    image: "netcore"
    volumes:
      - ./server:/var/www/server
    ports:
      - "5000:80"
    build:
      context: ./server
      dockerfile: Dockerfile